// Generated by scripts/export_web_languages.py — do not edit by hand.
// Kept in sync with ephemeral_core/config.py LANG_MAP (canonical
// languages, aliases, and dynamically-registered esolangs).
export const SUPPORTED_LANGUAGES = new Set([
  "05ab1e",
  "actionlint",
  "bash",
  "batch",
  "bf",
  "brainfuck",
  "c",
  "c++",
  "cc",
  "cjam",
  "cjs",
  "cl",
  "clj",
  "clojure",
  "cmd",
  "cob",
  "cobol",
  "common-lisp",
  "cpp",
  "cr",
  "crystal",
  "elixir",
  "ex",
  "exs",
  "f90",
  "f95",
  "fortran",
  "gh-runner",
  "gnucobol",
  "go",
  "golang",
  "golfscript",
  "haskell",
  "java",
  "javascript",
  "js",
  "julia",
  "latex",
  "lint-action",
  "lisp",
  "lolcode",
  "lua",
  "markdown",
  "matlab",
  "md",
  "mjs",
  "ml",
  "nim",
  "nimrod",
  "node",
  "npm",
  "npx",
  "numpy",
  "ocaml",
  "octave",
  "pandas",
  "pandoc",
  "pandoc-docx",
  "pandoc-pdf",
  "pdflatex",
  "perl",
  "php",
  "piet",
  "pl",
  "powershell",
  "prolog",
  "ps1",
  "pwsh",
  "py",
  "python",
  "pywine",
  "r",
  "ruby",
  "runner",
  "rust",
  "sbcl",
  "science",
  "sh",
  "swipl",
  "tex",
  "tiddlywiki",
  "tw",
  "tw5",
  "ubuntu-latest",
  "verilog",
  "wiki"
]);

export const CANONICAL_LANGUAGES = [
  "05ab1e",
  "actionlint",
  "bash",
  "brainfuck",
  "c",
  "cjam",
  "clojure",
  "cobol",
  "cpp",
  "crystal",
  "elixir",
  "fortran",
  "gh-runner",
  "go",
  "golfscript",
  "haskell",
  "java",
  "julia",
  "latex",
  "lisp",
  "lolcode",
  "lua",
  "nim",
  "node",
  "ocaml",
  "octave",
  "pandoc",
  "pandoc-docx",
  "pandoc-pdf",
  "perl",
  "php",
  "piet",
  "prolog",
  "pwsh",
  "python",
  "pywine",
  "r",
  "ruby",
  "rust",
  "science",
  "tiddlywiki",
  "verilog"
];

export const ALIAS_MAP = {
  "python": [
    "py"
  ],
  "node": [
    "cjs",
    "javascript",
    "js",
    "mjs",
    "npm",
    "npx"
  ],
  "bash": [
    "sh"
  ],
  "science": [
    "numpy",
    "pandas"
  ],
  "octave": [
    "matlab"
  ],
  "pwsh": [
    "batch",
    "cmd",
    "powershell",
    "ps1"
  ],
  "go": [
    "golang"
  ],
  "c": [
    "cc"
  ],
  "cpp": [
    "c++"
  ],
  "fortran": [
    "f90",
    "f95"
  ],
  "lisp": [
    "cl",
    "common-lisp",
    "sbcl"
  ],
  "clojure": [
    "clj"
  ],
  "elixir": [
    "ex",
    "exs"
  ],
  "ocaml": [
    "ml"
  ],
  "prolog": [
    "pl",
    "swipl"
  ],
  "crystal": [
    "cr"
  ],
  "nim": [
    "nimrod"
  ],
  "brainfuck": [
    "bf"
  ],
  "cobol": [
    "cob",
    "gnucobol"
  ],
  "tiddlywiki": [
    "tw",
    "tw5",
    "wiki"
  ],
  "latex": [
    "pdflatex",
    "tex"
  ],
  "pandoc": [
    "markdown",
    "md"
  ],
  "gh-runner": [
    "runner",
    "ubuntu-latest"
  ],
  "actionlint": [
    "lint-action"
  ]
};
