"""Export the web client's supported-language list from ephemeral_core.

Writes ``ephemeral-wasm-library/web/languages.js`` — a static ES module the
SPA imports to (a) badge fence-language declarations in the Run Code editor
and (b) remind users what's supported when an unknown language is submitted.
Run after changing ``ephemeral_core.config.LANG_MAP``.

Usage: python scripts/export_web_languages.py
"""
from __future__ import annotations

import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from ephemeral_core.config import LANG_MAP  # noqa: E402

OUT = ROOT / "ephemeral-wasm-library" / "web" / "languages.js"

# The parser lowercases every fence info string, so lower-case the keys.
canonical = sorted({k.lower() for k, v in LANG_MAP.items() if isinstance(v, dict)})

# Aliases (string entries) resolve to canonical targets. Drop any whose
# target isn't a real dict entry — e.g. 'spl' -> 'shakespeare': the parser
# resolves those to a bare image the receiver allowlist rejects, so they
# are NOT actually supported and shouldn't badge green. Also skip aliases
# that just restate their own canonical name ('R' -> 'r').
alias_map: dict[str, list[str]] = {}
for k, v in LANG_MAP.items():
    if not isinstance(v, str):
        continue
    target = v.lower()
    if target in canonical and k.lower() != target:
        alias_map.setdefault(target, []).append(k.lower())
for target in alias_map:
    alias_map[target].sort()

all_langs = sorted(set(canonical) | {a for als in alias_map.values() for a in als})

js = (
    "// Generated by scripts/export_web_languages.py — do not edit by hand.\n"
    "// Kept in sync with ephemeral_core/config.py LANG_MAP (canonical\n"
    "// languages, aliases, and dynamically-registered esolangs).\n"
    f"export const SUPPORTED_LANGUAGES = new Set({json.dumps(all_langs, indent=2)});\n\n"
    f"export const CANONICAL_LANGUAGES = {json.dumps(canonical, indent=2)};\n\n"
    f"export const ALIAS_MAP = {json.dumps(alias_map, indent=2)};\n"
)
OUT.write_text(js, encoding="utf-8")
n_aliases = sum(len(als) for als in alias_map.values())
print(f"wrote {len(all_langs)} languages ({len(canonical)} canonical, "
      f"{n_aliases} aliases) -> {OUT.relative_to(ROOT)}")
