/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_ephemeralclient_free: (a: number, b: number) => void;
export const base64_decode: (a: number, b: number) => [number, number, number, number];
export const ephemeralclient_create: (a: number, b: number, c: number, d: number) => any;
export const ephemeralclient_discover: (a: number, b: number, c: number) => any;
export const ephemeralclient_discover_node: (a: number, b: number, c: number, d: number, e: number) => any;
export const ephemeralclient_make_ticket: (a: number) => [number, number, number, number];
export const ephemeralclient_node_id: (a: number) => [number, number];
export const ephemeralclient_submit_job: (a: number, b: number, c: number, d: number, e: number, f: number, g: any) => any;
export const ephemeralclient_submit_job_to_node: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: any) => any;
export const __wbg_intounderlyingbytesource_free: (a: number, b: number) => void;
export const intounderlyingbytesource_autoAllocateChunkSize: (a: number) => number;
export const intounderlyingbytesource_cancel: (a: number) => void;
export const intounderlyingbytesource_pull: (a: number, b: any) => any;
export const intounderlyingbytesource_start: (a: number, b: any) => void;
export const intounderlyingbytesource_type: (a: number) => number;
export const __wbg_intounderlyingsink_free: (a: number, b: number) => void;
export const __wbg_intounderlyingsource_free: (a: number, b: number) => void;
export const intounderlyingsink_abort: (a: number, b: any) => any;
export const intounderlyingsink_close: (a: number) => any;
export const intounderlyingsink_write: (a: number, b: any) => any;
export const intounderlyingsource_cancel: (a: number) => void;
export const intounderlyingsource_pull: (a: number, b: any) => any;
export const ring_core_0_17_14__bn_mul_mont: (a: number, b: number, c: number, d: number, e: number, f: number) => void;
export const wasm_bindgen_1643520842561e64___convert__closures_____invoke___wasm_bindgen_1643520842561e64___JsValue__core_f0fd674eaa06beef___result__Result_____wasm_bindgen_1643520842561e64___JsError___true_: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen_1643520842561e64___convert__closures_____invoke___js_sys_98b73a3bc388ea69___Function_fn_wasm_bindgen_1643520842561e64___JsValue_____wasm_bindgen_1643520842561e64___sys__Undefined___js_sys_98b73a3bc388ea69___Function_fn_wasm_bindgen_1643520842561e64___JsValue_____wasm_bindgen_1643520842561e64___sys__Undefined_______true_: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen_1643520842561e64___convert__closures_____invoke___wasm_bindgen_1643520842561e64___JsValue______true_: (a: number, b: number, c: any) => void;
export const wasm_bindgen_1643520842561e64___convert__closures_____invoke___web_sys_80bb434be7765b15___features__gen_CloseEvent__CloseEvent______true_: (a: number, b: number, c: any) => void;
export const wasm_bindgen_1643520842561e64___convert__closures_____invoke___web_sys_80bb434be7765b15___features__gen_MessageEvent__MessageEvent______true_: (a: number, b: number, c: any) => void;
export const wasm_bindgen_1643520842561e64___convert__closures_____invoke_______true_: (a: number, b: number) => void;
export const wasm_bindgen_1643520842561e64___convert__closures_____invoke_______true__1_: (a: number, b: number) => void;
export const wasm_bindgen_1643520842561e64___convert__closures_____invoke_______true__2_: (a: number, b: number) => void;
export const wasm_bindgen_1643520842561e64___convert__closures_____invoke_______true__3_: (a: number, b: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_destroy_closure: (a: number, b: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_start: () => void;
